# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 放码过来
subtitle: 技术宅 huangyuan@huangyuanlove.com
description: 锱铢必较间接性奋发图强，睚眦必报持续性混吃等死
author: HuangYuan_xuan
language: zh-CN
email: huangyuan@huangyuanlove.com

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://blog.huangyuanlove.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 1
category: 1
tag: 1
# Server
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
port: 4000
server_ip: localhost
logger: false
logger_format: dev
# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY年MM月DD日
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next
exclude_generator:
# Extensions
Plugins:
  - hexo-generator-feed
  - hexo-generate-feed
  - hexo-generator-baidu-sitemap
  - hexo-generator-sitemap

#sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
    path: baidusitemap.xm
#Feed Atom
feed:
  type: atom
  path: atom.xml
  limit: 20

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
- type: git
  repository: git@github.com:huangyuanlove/huangyuanlove.github.io.git
  branch: master
- type: git
  repository: git@git.coding.net:huangyuanlove/huangyuanlove.git
  branch: master


# Swiftype Search Key
#swiftype_key: LoCFNsvjbeYQpYd-Wuxs

index_generator:
  per_page: 10

archive_generator:
  per_page: 20
  yearly: true
  monthly: true

tag_generator:
  per_page: 10

algolia:
  applicationID: 'LO7AODH922'
  apiKey: 'eef0d8a75f8bcbfe584416f372bf56e7'
  indexName: 'blog'
  chunkSize: 5000

# mermaid chart
mermaid: ## mermaid url https://github.com/knsv/mermaid
  enable: true  # default true
  version: "7.1.2" # default v7.1.2
  options:  # find more api options from https://github.com/knsv/mermaid/blob/master/src/mermaidAPI.js
    #startOnload: true  // default true

symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true
  exclude_codeblock: true
